/**
 * 종목명 → 티커 매핑 테이블
 * AI 인식 실패(ticker: null) 시 fallback으로 사용
 *
 * 국내 상장 ETF + 국내 주식: 한국 투자자 인기 상위
 * 해외 주식 + 해외 ETF: 한국 투자자 인기 상위 (ETF/레버리지는 풀네임 키 포함)
 */

// ─── 국내 상장 ETF ─────────────────────────────────────────────────────────
export const DOMESTIC_ETF_MAP: Record<string, string> = {
  // ── TIGER (미래에셋) ──────────────────────────────────────────────────────
  "TIGER 미국S&P500": "360750",
  "TIGER 미국나스닥100": "133690",
  "TIGER 미국나스닥100TR": "381170",
  "TIGER 미국S&P500TR": "448290",
  "TIGER 미국빅테크10": "453810",
  "TIGER 미국테크TOP10 INDXX": "381180",
  "TIGER 미국필라델피아반도체나스닥": "381190",
  "TIGER 반도체": "091230",
  "TIGER 2차전지테마": "305540",
  "TIGER 차이나항셍테크": "371460",
  "TIGER 일본니케이225": "241180",
  "TIGER 인도니프티50": "453990",
  "TIGER 글로벌리튬&2차전지SOLACTIVE": "394670",
  "TIGER 미국달러단기채권액티브": "432360",
  "TIGER 단기채권액티브": "157450",
  "TIGER MSCI Korea TR": "310970",
  "TIGER 코스피": "102110",
  "TIGER 코스피200": "102110",
  "TIGER 코스닥150": "232080",
  "TIGER 배당성장": "211560",
  "TIGER 미국채10년선물": "305080",
  "TIGER 미국채30년선물(H)": "304660",
  "TIGER 글로벌혁신블루칩TOP10": "448300",
  "TIGER 미국AI빅테크10": "476580",
  "TIGER S&P글로벌헬스케어(합성)": "143850",
  "TIGER 미국나스닥100레버리지(합성)": "133690", // 주의: 레버리지 별도
  "TIGER 200커버드콜5%OTM": "315960",
  "TIGER 200커버드콜ATM": "289480",
  "TIGER 글로벌BBIG": "365550",
  "TIGER 미국MSCI리츠(합성H)": "182480",
  "TIGER 유로스탁스50(합성H)": "195930",
  "TIGER 원유선물Enhanced(H)": "271060",
  "TIGER 금은선물(H)": "319870",
  "TIGER 단기통안채": "157450",
  "TIGER CD금리투자KIS(합성)": "452340",
  "TIGER 200에너지화학레버리지": "243880",
  "TIGER 미국나스닥100(H)": "381170",
  "TIGER 차이나전기차SOLACTIVE": "371470",

  // ── KODEX (삼성자산운용) ──────────────────────────────────────────────────
  "KODEX 미국S&P500TR": "379800",
  "KODEX 미국나스닥100TR": "379810",
  "KODEX 미국빅테크10(H)": "379800",
  "KODEX 레버리지": "122630",
  "KODEX 인버스": "114800",
  "KODEX 200": "069500",
  "KODEX 코스닥150": "229200",
  "KODEX 반도체": "091160",
  "KODEX 2차전지산업": "305720",
  "KODEX 일본반도체": "468370",
  "KODEX 인도Nifty50": "453930",
  "KODEX 차이나항셍테크": "371450",
  "KODEX 미국달러선물": "261240",
  "KODEX 단기채권": "153130",
  "KODEX 국고채3년": "114260",
  "KODEX 미국채울트라30년선물(H)": "304670",
  "KODEX 미국S&P고배당커버드콜(합성H)": "432980",
  "KODEX 글로벌반도체": "453940",
  "KODEX 미국AI테크TOP10": "476550",
  "KODEX 미국나스닥100(H)": "379810",
  "KODEX 200TR": "278540",
  "KODEX 삼성그룹": "102780",
  "KODEX 배당성장": "211900",
  "KODEX MSCI한국": "273700",
  "KODEX 골드선물(H)": "132030",
  "KODEX 코스닥150레버리지": "233740",
  "KODEX 200선물인버스2X": "252670",
  "KODEX WTI원유선물(H)": "261220",
  "KODEX 미국채10년선물": "308620",
  "KODEX 은선물(H)": "319870",
  "KODEX CD금리액티브(합성)": "461580",
  "KODEX 미국나스닥100레버리지(합성H)": "409820",
  "KODEX 미국S&P500레버리지(합성H)": "439870",
  "KODEX Top5PlusTR": "438900",
  "KODEX 한국부동산리츠인프라": "432320",
  "KODEX iSelect배터리소재": "395390",
  "KODEX 미국배당커버드콜액티브": "441640",

  // ── ACE (한국투자신탁) ────────────────────────────────────────────────────
  "ACE 미국S&P500": "360200",
  "ACE 미국나스닥100": "367380",
  "ACE 미국S&P500TR": "360200",
  "ACE 미국빅테크TOP7 Plus": "465640",
  "ACE 미국반도체": "465650",
  "ACE 인도시장대표BharatiAXA": "448930",
  "ACE 일본반도체": "465630",
  "ACE KRX금현물": "411060",
  "ACE 미국30년국채액티브(H)": "449170",
  "ACE 국고채10년": "365850",
  "ACE 테슬라밸류체인액티브": "459800",
  "ACE 글로벌반도체TOP4 Plus SOLACTIVE": "396500",
  "ACE 미국나스닥100레버리지(합성H)": "409810",
  "ACE 미국500밸류커버드콜": "477620",
  "ACE 미국빅테크커버드콜": "477630",
  "ACE CD금리&머니마켓액티브": "453910",
  "ACE 미국달러SOFR금리(합성)": "435420",

  // ── KINDEX (한국투자신탁, 구 브랜드) ────────────────────────────────────
  "KINDEX 미국S&P500": "360200",
  "KINDEX 미국나스닥100": "367380",

  // ── HANARO (NH아문디) ─────────────────────────────────────────────────────
  "HANARO 미국빅테크10": "458730",
  "HANARO 미국S&P500": "448860",
  "HANARO 미국나스닥100": "448870",
  "HANARO 글로벌반도체TOP10 SOLACTIVE": "396530",
  "HANARO 인도S&P500": "458730",
  "HANARO 미국채30년액티브(H)": "449710",
  "HANARO 200": "293180",
  "HANARO 코스닥150": "293190",
  "HANARO 글로벌럭셔리S&P(합성)": "395180",

  // ── SOL (신한자산운용) ────────────────────────────────────────────────────
  "SOL 미국S&P500": "447770",
  "SOL 미국나스닥100": "447780",
  "SOL 미국배당다우존스": "446720",
  "SOL 미국배당다우존스(H)": "446730",
  "SOL 금리우대US달러RP": "427250",
  "SOL 한국형글로벌반도체액티브": "448800",
  "SOL 미국나스닥100레버리지(합성H)": "468320",
  "SOL 미국30년국채커버드콜(합성H)": "476630",
  "SOL 미국테크TOP10": "476560",
  "SOL 미국TOP5채권혼합50": "447620",

  // ── RISE (KB자산운용, 구 KBSTAR) ─────────────────────────────────────────
  "RISE 미국S&P500": "379760",
  "RISE 미국나스닥100": "379770",
  "RISE 200": "148020",
  "RISE 글로벌데이터센터리츠나스닥(합성H)": "426870",
  "RISE 미국배당다우존스": "446710",
  "RISE 미국AI밸류체인액티브": "476590",
  "RISE 미국30년국채액티브(H)": "449730",
  "KBSTAR 미국S&P500": "379760",
  "KBSTAR 미국나스닥100": "379770",
  "KBSTAR 200": "069660",

  // ── ARIRANG (한화자산운용) ───────────────────────────────────────────────
  "ARIRANG 미국S&P500": "453950",
  "ARIRANG 고배당주": "161510",
  "ARIRANG 미국나스닥100": "453960",
  "ARIRANG 미국장기국채액티브(H)": "449750",

  // ── TIMEFOLIO (타임폴리오) ────────────────────────────────────────────────
  "TIMEFOLIO 미국나스닥100액티브": "441640",
  "TIMEFOLIO Korea플러스배당액티브": "441650",

  // ── BIG (한화자산운용) ────────────────────────────────────────────────────
  "BIG 미국S&P500": "476540",
  "BIG 미국나스닥100": "476530",

  // ── PLUS (한화자산운용) ────────────────────────────────────────────────────
  "PLUS 고배당주": "161510",
};

// ─── 국내 주식 ─────────────────────────────────────────────────────────────
export const DOMESTIC_STOCK_MAP: Record<string, string> = {
  // ── 반도체/IT ──────────────────────────────────────────────────────────────
  "삼성전자": "005930",
  "SK하이닉스": "000660",
  "삼성전자우": "005935",
  "DB하이텍": "000990",
  "리노공업": "058470",
  "HPSP": "403870",
  "한미반도체": "042700",
  "주성엔지니어링": "036930",
  "이오테크닉스": "039030",
  "원익IPS": "240810",
  "유진테크": "084370",
  "피에스케이": "319660",
  "코미코": "183300",
  "하나마이크론": "067310",
  "네패스": "033640",

  // ── 2차전지 ───────────────────────────────────────────────────────────────
  "LG에너지솔루션": "373220",
  "삼성SDI": "006400",
  "LG화학": "051910",
  "에코프로비엠": "247540",
  "에코프로": "086520",
  "포스코퓨처엠": "003670",
  "엘앤에프": "066970",
  "코스모신소재": "005070",
  "나노신소재": "121600",
  "천보": "278280",
  "SK아이이테크놀로지": "361610",
  "솔루스첨단소재": "336370",

  // ── 바이오/제약 ───────────────────────────────────────────────────────────
  "삼성바이오로직스": "207940",
  "셀트리온": "068270",
  "셀트리온헬스케어": "068270",
  "유한양행": "000100",
  "한미약품": "128940",
  "대웅제약": "069620",
  "종근당": "185750",
  "녹십자": "006280",
  "동아에스티": "170900",
  "보령": "003850",
  "HK이노엔": "195940",
  "알테오젠": "196170",

  // ── 금융 ──────────────────────────────────────────────────────────────────
  "KB금융": "105560",
  "신한지주": "055550",
  "하나금융지주": "086790",
  "우리금융지주": "316140",
  "메리츠금융지주": "138040",
  "삼성화재": "000810",
  "DB손해보험": "005830",
  "한국금융지주": "071050",
  "키움증권": "039490",
  "미래에셋증권": "006800",
  "삼성증권": "016360",
  "NH투자증권": "005940",

  // ── 자동차/운송 ───────────────────────────────────────────────────────────
  "현대차": "005380",
  "기아": "000270",
  "현대모비스": "012330",
  "현대글로비스": "086280",
  "한온시스템": "018880",
  "HL만도": "204320",
  "현대위아": "011210",
  "대한항공": "003490",
  "하나투어": "039130",
  "제주항공": "089590",
  "HMM": "011200",

  // ── 인터넷/플랫폼 ─────────────────────────────────────────────────────────
  "NAVER": "035420",
  "카카오": "035720",
  "카카오뱅크": "323410",
  "카카오페이": "377300",
  "크래프톤": "259960",
  "넷마블": "251270",
  "엔씨소프트": "036570",
  "펄어비스": "263750",
  "컴투스": "078340",
  "카카오게임즈": "293490",

  // ── 에너지/화학/소재 ──────────────────────────────────────────────────────
  "포스코홀딩스": "005490",
  "현대제철": "004020",
  "고려아연": "010130",
  "OCI홀딩스": "010060",
  "롯데케미칼": "011170",
  "금호석유": "011780",
  "한화솔루션": "009830",
  "HD현대": "267250",
  "SK이노베이션": "096770",
  "에쓰오일": "010950",
  "GS": "078930",

  // ── 건설/리츠 ─────────────────────────────────────────────────────────────
  "삼성물산": "028260",
  "현대건설": "000720",
  "DL이앤씨": "375500",
  "GS건설": "006360",
  "롯데쇼핑": "023530",
  "신세계": "004170",
  "이마트": "139480",

  // ── 방산/항공우주 ─────────────────────────────────────────────────────────
  "한화에어로스페이스": "012450",
  "LIG넥스원": "079550",
  "현대로템": "064350",
  "한국항공우주": "047810",
  "이노스페이스": "462350",

  // ── 통신 ──────────────────────────────────────────────────────────────────
  "SK텔레콤": "017670",
  "KT": "030200",
  "LG유플러스": "032640",

  // ── 기타 대형주 ───────────────────────────────────────────────────────────
  "삼성생명": "032830",
  "롯데지주": "004990",
  "CJ제일제당": "097950",
  "오리온": "271560",
  "농심": "004370",
  "하이브": "352820",
  "SM엔터테인먼트": "041510",
  "JYP엔터테인먼트": "035900",
  "YG엔터테인먼트": "122870",

  // ── 반도체/장비 추가 ──────────────────────────────────────────────────────
  "삼성전기": "009150",
  "LG이노텍": "011070",
  "SK스퀘어": "402340",
  "레이크머티리얼즈": "281740",
  "ISC": "095340",
  "테크윙": "089030",
  "디이엔티": "079810",
  "파크시스템스": "140860",
  "하이비젼시스템": "126700",
  "오로스테크놀로지": "322310",
  "케이씨텍": "281820",
  "티씨케이": "064760",
  "와이씨켐": "112290",
  "솔브레인": "357780",
  "동진쎄미켐": "005290",
  "SK실트론": "031610",
  "원익머트리얼즈": "104830",
  "네오세미테크": "253590",
  "에스앤에스텍": "101490",
  "두산테스나": "317330",

  // ── 2차전지 추가 ──────────────────────────────────────────────────────────
  "피엔티": "137400",
  "일진머티리얼즈": "020150",
  "상신이디피": "041520",
  "엔켐": "348370",
  "에코앤드림": "101360",
  "후성": "093370",
  "씨아이에스": "222080",
  "원익피앤이": "217820",
  "신흥에스이씨": "243840",
  "성일하이텍": "365340",
  "코스모화학": "005420",
  "이엔드디": "101400",

  // ── 바이오/제약 추가 ──────────────────────────────────────────────────────
  "리가켐바이오": "141080",
  "오스코텍": "039200",
  "제넥신": "095700",
  "에이비엘바이오": "298380",
  "메디톡스": "086900",
  "휴젤": "145020",
  "클래시스": "214150",
  "파마리서치": "214450",
  "동국제약": "086450",
  "일동제약": "249420",
  "보령제약": "003850",
  "JW중외제약": "001060",
  "광동제약": "009290",
  "영진약품": "003520",
  "신풍제약": "019170",
  "테고사이언스": "191420",
  "압타바이오": "293780",
  "올릭스": "226950",
  "에스티팜": "237690",
  "한올바이오파마": "009420",

  // ── 방산/항공우주 추가 ────────────────────────────────────────────────────
  "한화시스템": "272210",
  "빅텍": "065350",
  "퍼스텍": "010820",
  "스페코": "013810",
  "휴니드": "005870",

  // ── 금융 추가 ─────────────────────────────────────────────────────────────
  "삼성카드": "029780",
  "현대카드": "060980",
  "케이뱅크": "279220",
  "교보증권": "030610",
  "대신증권": "003540",
  "한국투자증권": "071050",
  "신한투자증권": "001500",
  "현대해상": "001450",
  "KB손해보험": "105560",
  "롯데손해보험": "000400",

  // ── 인터넷/플랫폼/게임 추가 ──────────────────────────────────────────────
  "더블유게임즈": "192080",
  "위메이드": "112040",
  "시프트업": "462870",
  "데브시스터즈": "194480",
  "스마일게이트": "293660",
  "넥슨게임즈": "225570",
  "네오위즈": "095660",
  "웹젠": "069080",
  "NHN": "181710",
  "카카오스타일": "451800",

  // ── 유통/소비재 ───────────────────────────────────────────────────────────
  "BGF리테일": "282330",
  "GS리테일": "007070",
  "현대백화점": "069960",
  "롯데백화점": "023530",
  "CJ ENM": "035760",
  "CJENM": "035760",
  "스튜디오드래곤": "253450",
  "하이트진로": "000080",
  "오비맥주": "014820",
  "CJ대한통운": "000120",

  // ── 건설/부동산/리츠 추가 ────────────────────────────────────────────────
  "HDC현대산업개발": "294870",
  "SK에코플랜트": "001740",
  "대우건설": "047040",
  "포스코인터내셔널": "047050",
  "맥쿼리인프라": "088980",
  "제이알글로벌리츠": "348950",
  "ESR켄달스퀘어리츠": "365550",
  "롯데리츠": "330590",
  "SK리츠": "395400",
  "신한알파리츠": "293940",

  // ── 에너지/소재/화학 추가 ────────────────────────────────────────────────
  "효성첨단소재": "298050",
  "효성화학": "298000",
  "금호타이어": "073240",
  "한국타이어앤테크놀로지": "161390",
  "넥센타이어": "002350",
  "OCI": "010060",
  "태광산업": "003240",
  "SK케미칼": "285130",
  "LG솔루션": "373220",
  "코오롱인더": "120110",
};

// ─── 해외 주식 ─────────────────────────────────────────────────────────────
export const FOREIGN_STOCK_MAP: Record<string, string> = {
  // ── 미국 빅테크/반도체 ───────────────────────────────────────────────────
  "엔비디아": "NVDA",
  "Nvidia": "NVDA",
  "테슬라": "TSLA",
  "Tesla": "TSLA",
  "애플": "AAPL",
  "Apple": "AAPL",
  "마이크로소프트": "MSFT",
  "Microsoft": "MSFT",
  "아마존": "AMZN",
  "Amazon": "AMZN",
  "알파벳": "GOOGL",
  "구글": "GOOGL",
  "Google": "GOOGL",
  "Alphabet": "GOOGL",
  "메타": "META",
  "Meta": "META",
  "넷플릭스": "NFLX",
  "Netflix": "NFLX",
  "AMD": "AMD",
  "인텔": "INTC",
  "Intel": "INTC",
  "브로드컴": "AVGO",
  "Broadcom": "AVGO",
  "TSMC": "TSM",
  "퀄컴": "QCOM",
  "Qualcomm": "QCOM",
  "어플라이드머티리얼즈": "AMAT",
  "Applied Materials": "AMAT",
  "마이크론": "MU",
  "Micron": "MU",
  "팔란티어": "PLTR",
  "Palantir": "PLTR",
  "슈퍼마이크로컴퓨터": "SMCI",
  "Super Micro Computer": "SMCI",
  "ARM": "ARM",
  "ASML": "ASML",
  "램리서치": "LRCX",
  "Lam Research": "LRCX",
  "KLA": "KLAC",
  "테라다인": "TER",
  "ON Semiconductor": "ON",

  // ── 미국 금융 ────────────────────────────────────────────────────────────
  "버크셔해서웨이": "BRK.B",
  "Berkshire Hathaway": "BRK.B",
  "JP모건": "JPM",
  "JPMorgan": "JPM",
  "비자": "V",
  "Visa": "V",
  "마스터카드": "MA",
  "Mastercard": "MA",
  "뱅크오브아메리카": "BAC",
  "Bank of America": "BAC",
  "웰스파고": "WFC",
  "Wells Fargo": "WFC",
  "골드만삭스": "GS",
  "Goldman Sachs": "GS",
  "모건스탠리": "MS",
  "Morgan Stanley": "MS",
  "코인베이스": "COIN",
  "Coinbase": "COIN",
  "로빈후드": "HOOD",
  "Robinhood": "HOOD",
  "씨티그룹": "C",
  "Citigroup": "C",
  "찰스슈왑": "SCHW",
  "Charles Schwab": "SCHW",
  "블랙록": "BLK",
  "BlackRock": "BLK",

  // ── 미국 소비재 ──────────────────────────────────────────────────────────
  "월마트": "WMT",
  "Walmart": "WMT",
  "코스트코": "COST",
  "Costco": "COST",
  "나이키": "NKE",
  "Nike": "NKE",
  "스타벅스": "SBUX",
  "Starbucks": "SBUX",
  "맥도날드": "MCD",
  "McDonald's": "MCD",
  "홈디포": "HD",
  "Home Depot": "HD",
  "타겟": "TGT",
  "Target": "TGT",
  "룰루레몬": "LULU",
  "Lululemon": "LULU",
  "치폴레": "CMG",
  "Chipotle": "CMG",

  // ── 미국 헬스케어 ────────────────────────────────────────────────────────
  "존슨앤드존슨": "JNJ",
  "Johnson & Johnson": "JNJ",
  "화이자": "PFE",
  "Pfizer": "PFE",
  "일라이릴리": "LLY",
  "Eli Lilly": "LLY",
  "유나이티드헬스": "UNH",
  "UnitedHealth": "UNH",
  "애브비": "ABBV",
  "AbbVie": "ABBV",
  "모더나": "MRNA",
  "Moderna": "MRNA",
  "길리어드사이언스": "GILD",
  "Gilead Sciences": "GILD",
  "암젠": "AMGN",
  "Amgen": "AMGN",
  "리제네론": "REGN",
  "Regeneron": "REGN",
  "인튜이티브서지컬": "ISRG",
  "Intuitive Surgical": "ISRG",
  "노보노디스크": "NVO",
  "Novo Nordisk": "NVO",

  // ── 미국 에너지 ──────────────────────────────────────────────────────────
  "엑슨모빌": "XOM",
  "ExxonMobil": "XOM",
  "쉐브론": "CVX",
  "Chevron": "CVX",
  "캐터필러": "CAT",
  "Caterpillar": "CAT",
  "유니온퍼시픽": "UNP",
  "Union Pacific": "UNP",

  // ── 미국 소프트웨어/클라우드 ─────────────────────────────────────────────
  "세일즈포스": "CRM",
  "Salesforce": "CRM",
  "오라클": "ORCL",
  "Oracle": "ORCL",
  "어도비": "ADBE",
  "Adobe": "ADBE",
  "인튜이트": "INTU",
  "Intuit": "INTU",
  "서비스나우": "NOW",
  "ServiceNow": "NOW",
  "스노우플레이크": "SNOW",
  "Snowflake": "SNOW",
  "데이터독": "DDOG",
  "Datadog": "DDOG",
  "크라우드스트라이크": "CRWD",
  "CrowdStrike": "CRWD",
  "클라우드플레어": "NET",
  "Cloudflare": "NET",
  "몽고DB": "MDB",
  "MongoDB": "MDB",
  "줌": "ZM",
  "Zoom": "ZM",
  "페이팔": "PYPL",
  "PayPal": "PYPL",
  "쇼피파이": "SHOP",
  "Shopify": "SHOP",
  "스퀘어": "SQ",
  "Block": "SQ",
  "스포티파이": "SPOT",
  "Spotify": "SPOT",
  "에어비앤비": "ABNB",
  "Airbnb": "ABNB",
  "우버": "UBER",
  "Uber": "UBER",
  "IBM": "IBM",
  "델": "DELL",
  "Dell": "DELL",

  // ── 미국 레버리지/인버스 ETF (풀네임 포함) ──────────────────────────────
  "TQQQ": "TQQQ",
  "ProShares UltraPro QQQ": "TQQQ",
  "SOXL": "SOXL",
  "Direxion Daily Semiconductor Bull 3X Shares": "SOXL",
  "SOXL 3배": "SOXL",
  "TSLL": "TSLL",
  "Direxion Daily TSLA Bull 2X Shares": "TSLL",
  "Direxion TSLA Daily 2X": "TSLL",
  "테슬라 2X": "TSLL",
  "NVDL": "NVDL",
  "GraniteShares 2x Long NVDA Daily ETF": "NVDL",
  "엔비디아 2X": "NVDL",
  "FNGU": "FNGU",
  "MicroSectors FANG+ Index 3X Leveraged ETN": "FNGU",
  "TECL": "TECL",
  "Direxion Daily Technology Bull 3X Shares": "TECL",
  "기술주 3배": "TECL",
  "UPRO": "UPRO",
  "ProShares UltraPro S&P500": "UPRO",
  "S&P500 3배": "UPRO",
  "SPXL": "SPXL",
  "Direxion Daily S&P 500 Bull 3X Shares": "SPXL",
  "LABU": "LABU",
  "Direxion Daily S&P Biotech Bull 3X Shares": "LABU",
  "SOXS": "SOXS",
  "Direxion Daily Semiconductor Bear 3X Shares": "SOXS",
  "SQQQ": "SQQQ",
  "ProShares UltraPro Short QQQ": "SQQQ",
  "나스닥 인버스 3배": "SQQQ",
  "TNA": "TNA",
  "Direxion Daily Small Cap Bull 3X Shares": "TNA",
  "WEBL": "WEBL",
  "Direxion Daily Dow Jones Internet Bull 3X Shares": "WEBL",
  "CURE": "CURE",
  "Direxion Daily Healthcare Bull 3X Shares": "CURE",
  "DPST": "DPST",
  "Direxion Daily Regional Banks Bull 3X Shares": "DPST",
  "FAS": "FAS",
  "Direxion Daily Financial Bull 3X Shares": "FAS",
  "NAIL": "NAIL",
  "Direxion Daily Homebuilders & Supplies Bull 3X Shares": "NAIL",
  "TPVG": "TPVG",
  "MSFL": "MSFL",
  "GraniteShares 2x Long MSFT Daily ETF": "MSFL",
  "마이크로소프트 2X": "MSFL",
  "AAPB": "AAPB",
  "GraniteShares 2x Long AAPL Daily ETF": "AAPB",
  "애플 2X": "AAPB",
  "AMZU": "AMZU",
  "GraniteShares 2x Long AMZN Daily ETF": "AMZU",
  "아마존 2X": "AMZU",
  "METL": "METL",
  "GraniteShares 2x Long META Daily ETF": "METL",
  "메타 2X": "METL",
  "PLTU": "PLTU",
  "GraniteShares 2x Long PLTR Daily ETF": "PLTU",
  "팔란티어 2X": "PLTU",
  "CONL": "CONL",
  "GraniteShares 2x Long COIN Daily ETF": "CONL",
  "코인베이스 2X": "CONL",

  // ── 미국 일반 ETF (풀네임 포함) ─────────────────────────────────────────
  "QQQ": "QQQ",
  "Invesco QQQ Trust": "QQQ",
  "나스닥100 ETF": "QQQ",
  "SPY": "SPY",
  "SPDR S&P 500 ETF Trust": "SPY",
  "VOO": "VOO",
  "Vanguard S&P 500 ETF": "VOO",
  "IVV": "IVV",
  "iShares Core S&P 500 ETF": "IVV",
  "VTI": "VTI",
  "Vanguard Total Stock Market ETF": "VTI",
  "SCHD": "SCHD",
  "Schwab US Dividend Equity ETF": "SCHD",
  "JEPI": "JEPI",
  "JPMorgan Equity Premium Income ETF": "JEPI",
  "JEPQ": "JEPQ",
  "JPMorgan Nasdaq Equity Premium Income ETF": "JEPQ",
  "QQQM": "QQQM",
  "Invesco Nasdaq 100 ETF": "QQQM",
  "CONY": "CONY",
  "YieldMax COIN Option Income Strategy ETF": "CONY",
  "MSFO": "MSFO",
  "YieldMax MSFT Option Income Strategy ETF": "MSFO",
  "NVDY": "NVDY",
  "YieldMax NVDA Option Income Strategy ETF": "NVDY",
  "TSLY": "TSLY",
  "YieldMax TSLA Option Income Strategy ETF": "TSLY",
  "AMZY": "AMZY",
  "YieldMax AMZN Option Income Strategy ETF": "AMZY",
  "GOOGY": "GOOGY",
  "YieldMax GOOGL Option Income Strategy ETF": "GOOGY",
  "APLY": "APLY",
  "YieldMax AAPL Option Income Strategy ETF": "APLY",
  "GLD": "GLD",
  "SPDR Gold Shares": "GLD",
  "금 ETF": "GLD",
  "IAU": "IAU",
  "iShares Gold Trust": "IAU",
  "SLV": "SLV",
  "iShares Silver Trust": "SLV",
  "은 ETF": "SLV",
  "TLT": "TLT",
  "iShares 20+ Year Treasury Bond ETF": "TLT",
  "미국채 20년 ETF": "TLT",
  "IEF": "IEF",
  "iShares 7-10 Year Treasury Bond ETF": "IEF",
  "BND": "BND",
  "Vanguard Total Bond Market ETF": "BND",
  "IBIT": "IBIT",
  "iShares Bitcoin Trust ETF": "IBIT",
  "비트코인 ETF": "IBIT",
  "FBTC": "FBTC",
  "Fidelity Wise Origin Bitcoin Fund": "FBTC",
  "ARKK": "ARKK",
  "ARK Innovation ETF": "ARKK",
  "ARKG": "ARKG",
  "ARK Genomic Revolution ETF": "ARKG",
  "SOXX": "SOXX",
  "iShares Semiconductor ETF": "SOXX",
  "SMH": "SMH",
  "VanEck Semiconductor ETF": "SMH",
  "XLK": "XLK",
  "Technology Select Sector SPDR Fund": "XLK",
  "XLF": "XLF",
  "Financial Select Sector SPDR Fund": "XLF",
  "XLE": "XLE",
  "Energy Select Sector SPDR Fund": "XLE",
  "KWEB": "KWEB",
  "KraneShares CSI China Internet ETF": "KWEB",
  "중국인터넷 ETF": "KWEB",
  "EWJ": "EWJ",
  "iShares MSCI Japan ETF": "EWJ",
  "일본 ETF": "EWJ",
  "EEM": "EEM",
  "iShares MSCI Emerging Markets ETF": "EEM",
  "신흥국 ETF": "EEM",
  "VEA": "VEA",
  "Vanguard FTSE Developed Markets ETF": "VEA",
  "INDA": "INDA",
  "iShares MSCI India ETF": "INDA",
  "인도 ETF": "INDA",
  "MCHI": "MCHI",
  "iShares MSCI China ETF": "MCHI",
  "중국 ETF": "MCHI",

  // ── 비트코인/크립토 관련주 ───────────────────────────────────────────────
  "비트마인": "BMNR",
  "Bit Digital": "BTBT",
  "BTBT": "BTBT",
  "마라톤디지털": "MARA",
  "Marathon Digital": "MARA",
  "MARA": "MARA",
  "라이엇플랫폼스": "RIOT",
  "Riot Platforms": "RIOT",
  "RIOT": "RIOT",
  "클린스파크": "CLSK",
  "CleanSpark": "CLSK",
  "CLSK": "CLSK",
  "코어사이언티픽": "CORZ",
  "Core Scientific": "CORZ",
  "CORZ": "CORZ",
  "아이리스에너지": "IREN",
  "Iris Energy": "IREN",
  "IREN": "IREN",
  "비트팜스": "BITF",
  "Bitfarms": "BITF",
  "BITF": "BITF",
  "사이퍼마이닝": "CIFR",
  "Cipher Mining": "CIFR",
  "CIFR": "CIFR",
  "테라울프": "WULF",
  "TeraWulf": "WULF",
  "WULF": "WULF",
  "허트8": "HUT",
  "Hut 8": "HUT",
  "HUT": "HUT",
  "스트라티스": "STRAT",
  "갤럭시디지털": "GLXY",
  "Galaxy Digital": "GLXY",

  // ── AI/데이터센터/반도체 추가 ─────────────────────────────────────────────
  "사운드하운드": "SOUN",
  "SoundHound": "SOUN",
  "SOUN": "SOUN",
  "아이온Q": "IONQ",
  "IonQ": "IONQ",
  "IONQ": "IONQ",
  "퀀텀컴퓨팅": "QUBT",
  "Quantum Computing": "QUBT",
  "QUBT": "QUBT",
  "디웨이브퀀텀": "QBTS",
  "D-Wave Quantum": "QBTS",
  "QBTS": "QBTS",
  "리게티컴퓨팅": "RGTI",
  "Rigetti Computing": "RGTI",
  "RGTI": "RGTI",
  "퍼플렉시티": "PRPLX",
  "C3.ai": "AI",
  "AI": "AI",
  "어센드러닝": "ACLS",
  "Axcelis Technologies": "ACLS",
  "ACLS": "ACLS",
  "몬도리틱": "MRVI",
  "버티브홀딩스": "VRT",
  "Vertiv": "VRT",
  "VRT": "VRT",
  "비바시스템즈": "VEEV",
  "Veeva Systems": "VEEV",
  "VEEV": "VEEV",
  "워크데이": "WDAY",
  "Workday": "WDAY",
  "WDAY": "WDAY",

  // ── 미국 에너지/원자력 ───────────────────────────────────────────────────
  "오클로": "OKLO",
  "Oklo": "OKLO",
  "OKLO": "OKLO",
  "카멜롯에너지": "CEG",
  "컨스텔레이션에너지": "CEG",
  "Constellation Energy": "CEG",
  "CEG": "CEG",
  "뉴스케일파워": "SMR",
  "NuScale Power": "SMR",
  "SMR": "SMR",
  "탈렌에너지": "TLN",
  "Talen Energy": "TLN",
  "TLN": "TLN",
  "비스트라": "VST",
  "Vistra": "VST",
  "VST": "VST",

  // ── 미국 바이오/제약 추가 ─────────────────────────────────────────────────
  "웨이브라이프사이언스": "WVE",
  "리커전파마슈티컬스": "RXRX",
  "Recursion Pharmaceuticals": "RXRX",
  "RXRX": "RXRX",
  "알엑스오": "RXST",
  "아비나스": "ARVN",
  "Arvinas": "ARVN",
  "ARVN": "ARVN",
  "카탈리스트바이오사이언스": "MCRB",
  "벌칸바이오사이언스": "FULC",
  "크리스퍼테라퓨틱스": "CRSP",
  "CRISPR Therapeutics": "CRSP",
  "CRSP": "CRSP",
  "빔테라퓨틱스": "BEAM",
  "Beam Therapeutics": "BEAM",
  "BEAM": "BEAM",
  "에디타스메디신": "EDIT",
  "Editas Medicine": "EDIT",
  "EDIT": "EDIT",

  // ── 미국 소매/유통 추가 ──────────────────────────────────────────────────
  "크록스": "CROX",
  "Crocs": "CROX",
  "CROX": "CROX",
  "달러제너럴": "DG",
  "Dollar General": "DG",
  "DG": "DG",
  "달러트리": "DLTR",
  "Dollar Tree": "DLTR",
  "DLTR": "DLTR",
  "로스스토어즈": "ROST",
  "Ross Stores": "ROST",
  "ROST": "ROST",
  "TJX": "TJX",
  "TJX Companies": "TJX",

  // ── 미국 자동차 ──────────────────────────────────────────────────────────
  "포드": "F",
  "Ford": "F",
  "제너럴모터스": "GM",
  "General Motors": "GM",
  "GM": "GM",

  // ── 미국 금융 추가 ───────────────────────────────────────────────────────
  "누홀딩스": "NU",
  "Nu Holdings": "NU",
  "NU": "NU",
  "이토로": "ETOR",
  "클로버헬스": "CLOV",

  // ── 미국 우주/모빌리티/신성장 ────────────────────────────────────────────
  "리비안": "RIVN",
  "Rivian": "RIVN",
  "루시드": "LCID",
  "Lucid": "LCID",
  "로켓랩": "RKLB",
  "Rocket Lab": "RKLB",
  "AST스페이스모바일": "ASTS",
  "AST SpaceMobile": "ASTS",
  "조비에비에이션": "JOBY",
  "Joby Aviation": "JOBY",
  "버진갤럭틱": "SPCE",
  "Virgin Galactic": "SPCE",
  "마이크로스트래티지": "MSTR",
  "MicroStrategy": "MSTR",
  "스트라이프": "STRIPE",

  // ── 미국 핀테크/금융 ──────────────────────────────────────────────────────
  "소파이": "SOFI",
  "SoFi": "SOFI",
  "어펌": "AFRM",
  "Affirm": "AFRM",
  "업스타트": "UPST",
  "Upstart": "UPST",
  "마켓액세스": "MKTX",
  "MarketAxess": "MKTX",

  // ── 미국 소비재/미디어/여행 ───────────────────────────────────────────────
  "디즈니": "DIS",
  "Disney": "DIS",
  "부킹홀딩스": "BKNG",
  "Booking Holdings": "BKNG",
  "익스피디아": "EXPE",
  "Expedia": "EXPE",
  "리프트": "LYFT",
  "Lyft": "LYFT",
  "도어대시": "DASH",
  "DoorDash": "DASH",
  "핀터레스트": "PINS",
  "Pinterest": "PINS",
  "스냅": "SNAP",
  "Snap": "SNAP",
  "트위터X": "X",
  "레딧": "RDDT",
  "Reddit": "RDDT",

  // ── 미국 통신 ─────────────────────────────────────────────────────────────
  "AT&T": "T",
  "버라이즌": "VZ",
  "Verizon": "VZ",
  "티모바일": "TMUS",
  "T-Mobile": "TMUS",
  "컴캐스트": "CMCSA",
  "Comcast": "CMCSA",

  // ── 미국 필수소비재/생활용품 ─────────────────────────────────────────────
  "프록터앤드갬블": "PG",
  "Procter & Gamble": "PG",
  "코카콜라": "KO",
  "Coca-Cola": "KO",
  "펩시코": "PEP",
  "PepsiCo": "PEP",
  "필립모리스": "PM",
  "Philip Morris": "PM",
  "알트리아": "MO",
  "Altria": "MO",
  "콜게이트팜올리브": "CL",
  "Colgate-Palmolive": "CL",
  "킴벌리클라크": "KMB",
  "Kimberly-Clark": "KMB",
  "제너럴밀스": "GIS",
  "General Mills": "GIS",

  // ── 미국 산업/항공우주/방산 ──────────────────────────────────────────────
  "보잉": "BA",
  "Boeing": "BA",
  "레이시온": "RTX",
  "RTX": "RTX",
  "록히드마틴": "LMT",
  "Lockheed Martin": "LMT",
  "노스럽그루먼": "NOC",
  "Northrop Grumman": "NOC",
  "GE에어로스페이스": "GE",
  "GE Aerospace": "GE",
  "3M": "MMM",
  "허니웰": "HON",
  "Honeywell": "HON",
  "디어": "DE",
  "Deere": "DE",

  // ── 미국 부동산/인프라 리츠 ──────────────────────────────────────────────
  "아메리칸타워": "AMT",
  "American Tower": "AMT",
  "프롤로지스": "PLD",
  "Prologis": "PLD",
  "웰타워": "WELL",
  "Welltower": "WELL",
  "퍼블릭스토리지": "PSA",
  "Public Storage": "PSA",
  "리얼티인컴": "O",
  "Realty Income": "O",

  // ── 미국 추가 레버리지/인버스 ETF ───────────────────────────────────────
  "TSLQ": "TSLQ",
  "AXS TSLA Bear Daily ETF": "TSLQ",
  "NVDS": "NVDS",
  "T-Rex 2X Inverse NVDA Daily Target ETF": "NVDS",
  "QLD": "QLD",
  "ProShares Ultra QQQ": "QLD",
  "나스닥100 2배": "QLD",
  "SSO": "SSO",
  "ProShares Ultra S&P500": "SSO",
  "S&P500 2배": "SSO",
  "UDOW": "UDOW",
  "ProShares UltraPro Dow30": "UDOW",
  "FNGO": "FNGO",
  "MicroSectors FANG+ Index 2X Leveraged ETN": "FNGO",
  "BULZ": "BULZ",
  "MicroSectors Solactive FANG & Innovation 3X Leveraged ETN": "BULZ",
  "MSFU": "MSFU",
  "T-Rex 2X Long MSFT Daily Target ETF": "MSFU",
  "GOOGL 2X": "GGLL",
  "GGLL": "GGLL",
  "Direxion Daily GOOGL Bull 2X Shares": "GGLL",
  "AMZD": "AMZD",
  "Direxion Daily AMZN Bear 1X Shares": "AMZD",

  // ── 추가 YieldMax ETF ─────────────────────────────────────────────────────
  "OARK": "OARK",
  "YieldMax Innovation Option Income Strategy ETF": "OARK",
  "YMAG": "YMAG",
  "YieldMax Magnificent 7 Fund of Option Income ETFs": "YMAG",
  "YMAX": "YMAX",
  "YieldMax Universe Fund of Option Income ETFs": "YMAX",
  // ── 미국 추가 ETF ─────────────────────────────────────────────────────────
  "SPYG": "SPYG",
  "SPDR Portfolio S&P 500 Growth ETF": "SPYG",
  "VGT": "VGT",
  "Vanguard Information Technology ETF": "VGT",
  "QQQJ": "QQQJ",
  "Invesco NASDAQ Next Gen 100 ETF": "QQQJ",
  "SPDW": "SPDW",
  "SPDR Portfolio Developed World ex-US ETF": "SPDW",
  "VWO": "VWO",
  "Vanguard FTSE Emerging Markets ETF": "VWO",
  "신흥국ETF": "VWO",
  "ETHE": "ETHE",
  "Grayscale Ethereum Trust ETF": "ETHE",
  "이더리움ETF": "ETHE",
  "GBTC": "GBTC",
  "Grayscale Bitcoin Trust ETF": "GBTC",
  "FETH": "FETH",
  "Fidelity Ethereum Fund": "FETH",

  // ── 유럽 ─────────────────────────────────────────────────────────────────
  "LVMH": "MC",
  "ASML Holding": "ASML",
  "SAP": "SAP",
  "노바티스": "NVS",
  "Novartis": "NVS",
  "로슈": "RHHBY",
  "Roche": "RHHBY",
  "네슬레": "NSRGY",
  "Nestle": "NSRGY",
  "유니레버": "UL",
  "Unilever": "UL",
  "리오틴토": "RIO",
  "Rio Tinto": "RIO",
  "BHP": "BHP",
  "버버리": "BRBY",
  "Burberry": "BRBY",
  "페라리": "RACE",
  "Ferrari": "RACE",
};

// ─── 통합 매핑 (정규화 키) ──────────────────────────────────────────────────

function normalizeName(name: string): string {
  return name
    .replace(/[()（）\s\-·&…]/g, "")
    .replace(/\.+$/, "") // 뒷부분의 줄임표(.) 제거
    .toLowerCase();
}

const _allMap: Record<string, string> = {
  ...DOMESTIC_ETF_MAP,
  ...DOMESTIC_STOCK_MAP,
  ...FOREIGN_STOCK_MAP,
};

export const TICKER_MAP_NORMALIZED: Record<string, string> = Object.fromEntries(
  Object.entries(_allMap).map(([k, v]) => [normalizeName(k), v])
);

export function lookupTicker(name: string): string {
  const normalized = normalizeName(name);

  // 1단계: 정확한 일치
  if (TICKER_MAP_NORMALIZED[normalized]) {
    return TICKER_MAP_NORMALIZED[normalized];
  }

  // 4자 미만은 오탐 방지를 위해 fuzzy 매칭 생략
  if (normalized.length < 4) return "";

  // 2단계: prefix 매칭 — 입력이 등록된 키의 앞부분인 경우
  // 예: "kodex미국배당커버드콜액" → "kodex미국배당커버드콜액티브" 키에 매칭
  let bestPrefixMatch = "";
  let bestPrefixKeyLen = Infinity;
  for (const key of Object.keys(TICKER_MAP_NORMALIZED)) {
    if (key.startsWith(normalized) && key.length < bestPrefixKeyLen) {
      bestPrefixMatch = TICKER_MAP_NORMALIZED[key];
      bestPrefixKeyLen = key.length;
    }
  }
  if (bestPrefixMatch) return bestPrefixMatch;

  // 3단계: suffix 매칭 — 등록된 키가 입력의 앞부분인 경우 (입력이 키보다 긴 경우)
  // 예: "kodex미국배당커버드콜액티브etf" → "kodex미국배당커버드콜액티브" 키에 매칭
  let bestKeyPrefixMatch = "";
  let bestKeyPrefixLen = 0;
  for (const key of Object.keys(TICKER_MAP_NORMALIZED)) {
    if (normalized.startsWith(key) && key.length > bestKeyPrefixLen) {
      bestKeyPrefixMatch = TICKER_MAP_NORMALIZED[key];
      bestKeyPrefixLen = key.length;
    }
  }
  if (bestKeyPrefixMatch) return bestKeyPrefixMatch;

  // 4단계: 부분 일치 (includes) — 입력이 5자 이상이고 키에 포함되는 경우
  // 예: "미국필라델피아반도체" (앞의 TIGER 누락) -> "tiger미국필라델피아반도체나스닥" 매칭
  // 오탐 방지를 위해 입력 문자열이 최소 5자 이상일 때만 적용
  if (normalized.length >= 5) {
    let bestSubstringMatch = "";
    let bestSubstringKeyLen = Infinity;
    for (const key of Object.keys(TICKER_MAP_NORMALIZED)) {
      if (key.includes(normalized) && key.length < bestSubstringKeyLen) {
        bestSubstringMatch = TICKER_MAP_NORMALIZED[key];
        bestSubstringKeyLen = key.length;
      }
    }
    if (bestSubstringMatch) return bestSubstringMatch;
  }

  return "";
}
