/**
 * 종목명 → 티커 매핑 테이블
 * AI 인식 실패(ticker: null) 시 fallback으로 사용
 *
 * 국내(ETF·주식): KRX 전종목 마스터 사용 (src/lib/kr-master.ts)
 * 해외 주식 + 해외 ETF: 한국 투자자 인기 상위 (ETF/레버리지는 풀네임 키 포함)
 */

import { KR_NAME_TO_CODE } from "@/lib/kr-master";
import { US_NAME_TO_TICKER } from "@/lib/us-master";

// ─── 해외 주식 ─────────────────────────────────────────────────────────────
export const FOREIGN_STOCK_MAP: Record<string, string> = {
  // ── 미국 빅테크/반도체 ───────────────────────────────────────────────────
  "엔비디아": "NVDA",
  "Nvidia": "NVDA",
  "테슬라": "TSLA",
  "Tesla": "TSLA",
  "애플": "AAPL",
  "Apple": "AAPL",
  "마이크로소프트": "MSFT",
  "Microsoft": "MSFT",
  "아마존": "AMZN",
  "Amazon": "AMZN",
  "알파벳": "GOOGL",
  "구글": "GOOGL",
  "Google": "GOOGL",
  "Alphabet": "GOOGL",
  "메타": "META",
  "Meta": "META",
  "넷플릭스": "NFLX",
  "Netflix": "NFLX",
  "AMD": "AMD",
  "인텔": "INTC",
  "Intel": "INTC",
  "브로드컴": "AVGO",
  "Broadcom": "AVGO",
  "TSMC": "TSM",
  "퀄컴": "QCOM",
  "Qualcomm": "QCOM",
  "어플라이드머티리얼즈": "AMAT",
  "Applied Materials": "AMAT",
  "마이크론": "MU",
  "Micron": "MU",
  "팔란티어": "PLTR",
  "Palantir": "PLTR",
  "슈퍼마이크로컴퓨터": "SMCI",
  "Super Micro Computer": "SMCI",
  "ARM": "ARM",
  "ASML": "ASML",
  "램리서치": "LRCX",
  "Lam Research": "LRCX",
  "KLA": "KLAC",
  "테라다인": "TER",
  "ON Semiconductor": "ON",

  // ── 미국 금융 ────────────────────────────────────────────────────────────
  "버크셔해서웨이": "BRK.B",
  "Berkshire Hathaway": "BRK.B",
  "JP모건": "JPM",
  "JPMorgan": "JPM",
  "비자": "V",
  "Visa": "V",
  "마스터카드": "MA",
  "Mastercard": "MA",
  "뱅크오브아메리카": "BAC",
  "Bank of America": "BAC",
  "웰스파고": "WFC",
  "Wells Fargo": "WFC",
  "골드만삭스": "GS",
  "Goldman Sachs": "GS",
  "모건스탠리": "MS",
  "Morgan Stanley": "MS",
  "코인베이스": "COIN",
  "Coinbase": "COIN",
  "로빈후드": "HOOD",
  "Robinhood": "HOOD",
  "씨티그룹": "C",
  "Citigroup": "C",
  "찰스슈왑": "SCHW",
  "Charles Schwab": "SCHW",
  "블랙록": "BLK",
  "BlackRock": "BLK",

  // ── 미국 소비재 ──────────────────────────────────────────────────────────
  "월마트": "WMT",
  "Walmart": "WMT",
  "코스트코": "COST",
  "Costco": "COST",
  "나이키": "NKE",
  "Nike": "NKE",
  "스타벅스": "SBUX",
  "Starbucks": "SBUX",
  "맥도날드": "MCD",
  "McDonald's": "MCD",
  "홈디포": "HD",
  "Home Depot": "HD",
  "타겟": "TGT",
  "Target": "TGT",
  "룰루레몬": "LULU",
  "Lululemon": "LULU",
  "치폴레": "CMG",
  "Chipotle": "CMG",

  // ── 미국 헬스케어 ────────────────────────────────────────────────────────
  "존슨앤드존슨": "JNJ",
  "Johnson & Johnson": "JNJ",
  "화이자": "PFE",
  "Pfizer": "PFE",
  "일라이릴리": "LLY",
  "Eli Lilly": "LLY",
  "유나이티드헬스": "UNH",
  "UnitedHealth": "UNH",
  "애브비": "ABBV",
  "AbbVie": "ABBV",
  "모더나": "MRNA",
  "Moderna": "MRNA",
  "길리어드사이언스": "GILD",
  "Gilead Sciences": "GILD",
  "암젠": "AMGN",
  "Amgen": "AMGN",
  "리제네론": "REGN",
  "Regeneron": "REGN",
  "인튜이티브서지컬": "ISRG",
  "Intuitive Surgical": "ISRG",
  "노보노디스크": "NVO",
  "Novo Nordisk": "NVO",

  // ── 미국 에너지 ──────────────────────────────────────────────────────────
  "엑슨모빌": "XOM",
  "ExxonMobil": "XOM",
  "쉐브론": "CVX",
  "Chevron": "CVX",
  "캐터필러": "CAT",
  "Caterpillar": "CAT",
  "유니온퍼시픽": "UNP",
  "Union Pacific": "UNP",

  // ── 미국 소프트웨어/클라우드 ─────────────────────────────────────────────
  "세일즈포스": "CRM",
  "Salesforce": "CRM",
  "오라클": "ORCL",
  "Oracle": "ORCL",
  "어도비": "ADBE",
  "Adobe": "ADBE",
  "인튜이트": "INTU",
  "Intuit": "INTU",
  "서비스나우": "NOW",
  "ServiceNow": "NOW",
  "스노우플레이크": "SNOW",
  "Snowflake": "SNOW",
  "데이터독": "DDOG",
  "Datadog": "DDOG",
  "크라우드스트라이크": "CRWD",
  "CrowdStrike": "CRWD",
  "클라우드플레어": "NET",
  "Cloudflare": "NET",
  "몽고DB": "MDB",
  "MongoDB": "MDB",
  "줌": "ZM",
  "Zoom": "ZM",
  "페이팔": "PYPL",
  "PayPal": "PYPL",
  "쇼피파이": "SHOP",
  "Shopify": "SHOP",
  "스퀘어": "SQ",
  "Block": "SQ",
  "스포티파이": "SPOT",
  "Spotify": "SPOT",
  "에어비앤비": "ABNB",
  "Airbnb": "ABNB",
  "우버": "UBER",
  "Uber": "UBER",
  "IBM": "IBM",
  "델": "DELL",
  "Dell": "DELL",

  // ── 미국 레버리지/인버스 ETF (풀네임 포함) ──────────────────────────────
  "TQQQ": "TQQQ",
  "ProShares UltraPro QQQ": "TQQQ",
  "SOXL": "SOXL",
  "Direxion Daily Semiconductor Bull 3X Shares": "SOXL",
  "SOXL 3배": "SOXL",
  "TSLL": "TSLL",
  "Direxion Daily TSLA Bull 2X Shares": "TSLL",
  "Direxion TSLA Daily 2X": "TSLL",
  "테슬라 2X": "TSLL",
  "NVDL": "NVDL",
  "GraniteShares 2x Long NVDA Daily ETF": "NVDL",
  "엔비디아 2X": "NVDL",
  "FNGU": "FNGU",
  "MicroSectors FANG+ Index 3X Leveraged ETN": "FNGU",
  "TECL": "TECL",
  "Direxion Daily Technology Bull 3X Shares": "TECL",
  "기술주 3배": "TECL",
  "UPRO": "UPRO",
  "ProShares UltraPro S&P500": "UPRO",
  "S&P500 3배": "UPRO",
  "SPXL": "SPXL",
  "Direxion Daily S&P 500 Bull 3X Shares": "SPXL",
  "LABU": "LABU",
  "Direxion Daily S&P Biotech Bull 3X Shares": "LABU",
  "SOXS": "SOXS",
  "Direxion Daily Semiconductor Bear 3X Shares": "SOXS",
  "SQQQ": "SQQQ",
  "ProShares UltraPro Short QQQ": "SQQQ",
  "나스닥 인버스 3배": "SQQQ",
  "TNA": "TNA",
  "Direxion Daily Small Cap Bull 3X Shares": "TNA",
  "WEBL": "WEBL",
  "Direxion Daily Dow Jones Internet Bull 3X Shares": "WEBL",
  "CURE": "CURE",
  "Direxion Daily Healthcare Bull 3X Shares": "CURE",
  "DPST": "DPST",
  "Direxion Daily Regional Banks Bull 3X Shares": "DPST",
  "FAS": "FAS",
  "Direxion Daily Financial Bull 3X Shares": "FAS",
  "NAIL": "NAIL",
  "Direxion Daily Homebuilders & Supplies Bull 3X Shares": "NAIL",
  "TPVG": "TPVG",
  "MSFL": "MSFL",
  "GraniteShares 2x Long MSFT Daily ETF": "MSFL",
  "마이크로소프트 2X": "MSFL",
  "AAPB": "AAPB",
  "GraniteShares 2x Long AAPL Daily ETF": "AAPB",
  "애플 2X": "AAPB",
  "AMZU": "AMZU",
  "GraniteShares 2x Long AMZN Daily ETF": "AMZU",
  "아마존 2X": "AMZU",
  "METL": "METL",
  "GraniteShares 2x Long META Daily ETF": "METL",
  "메타 2X": "METL",
  "PLTU": "PLTU",
  "GraniteShares 2x Long PLTR Daily ETF": "PLTU",
  "팔란티어 2X": "PLTU",
  "CONL": "CONL",
  "GraniteShares 2x Long COIN Daily ETF": "CONL",
  "코인베이스 2X": "CONL",

  // ── 미국 일반 ETF (풀네임 + 한글명 포함) ────────────────────────────────
  "QQQ": "QQQ",
  "Invesco QQQ Trust": "QQQ",
  "나스닥100 ETF": "QQQ",
  "QQQ 인베스코 ETF": "QQQ",
  "인베스코 QQQ ETF": "QQQ",
  "인베스코나스닥ETF": "QQQ",
  "SPY": "SPY",
  "SPDR S&P 500 ETF Trust": "SPY",
  "S&P500 SPDR ETF": "SPY",
  "VOO": "VOO",
  "Vanguard S&P 500 ETF": "VOO",
  "S&P 500 뱅가드 ETF": "VOO",
  "뱅가드 S&P 500 ETF": "VOO",
  "뱅가드S&P500ETF": "VOO",
  "IVV": "IVV",
  "iShares Core S&P 500 ETF": "IVV",
  "아이쉐어즈 S&P500 ETF": "IVV",
  "VTI": "VTI",
  "Vanguard Total Stock Market ETF": "VTI",
  "뱅가드 토탈마켓 ETF": "VTI",
  "SCHD": "SCHD",
  "Schwab US Dividend Equity ETF": "SCHD",
  "슈왑 미국배당 ETF": "SCHD",
  "JEPI": "JEPI",
  "JPMorgan Equity Premium Income ETF": "JEPI",
  "JP모건 프리미엄인컴 ETF": "JEPI",
  "JEPQ": "JEPQ",
  "JPMorgan Nasdaq Equity Premium Income ETF": "JEPQ",
  "JP모건 나스닥 프리미엄인컴 ETF": "JEPQ",
  "QQQM": "QQQM",
  "Invesco Nasdaq 100 ETF": "QQQM",
  "나스닥 100 인베스코 ETF": "QQQM",
  "인베스코 나스닥 100 ETF": "QQQM",
  "SPYM": "SPYM",
  "SPDR Portfolio S&P 500 ETF": "SPYM",
  "STATE STREET SPDR PORTFOLIO S&P 500": "SPYM",
  "State Street SPDR Portfolio S&P 500": "SPYM",
  "스테이트스트리트 S&P500 ETF": "SPYM",
  "SPLG": "SPLG",
  "SPDR Portfolio Large Cap ETF": "SPLG",
  "CONY": "CONY",
  "YieldMax COIN Option Income Strategy ETF": "CONY",
  "MSFO": "MSFO",
  "YieldMax MSFT Option Income Strategy ETF": "MSFO",
  "NVDY": "NVDY",
  "YieldMax NVDA Option Income Strategy ETF": "NVDY",
  "TSLY": "TSLY",
  "YieldMax TSLA Option Income Strategy ETF": "TSLY",
  "AMZY": "AMZY",
  "YieldMax AMZN Option Income Strategy ETF": "AMZY",
  "GOOGY": "GOOGY",
  "YieldMax GOOGL Option Income Strategy ETF": "GOOGY",
  "APLY": "APLY",
  "YieldMax AAPL Option Income Strategy ETF": "APLY",
  "GLD": "GLD",
  "SPDR Gold Shares": "GLD",
  "금 ETF": "GLD",
  "금현물 ETF": "GLD",
  "IAU": "IAU",
  "iShares Gold Trust": "IAU",
  "아이쉐어즈 금 ETF": "IAU",
  "SLV": "SLV",
  "iShares Silver Trust": "SLV",
  "은 ETF": "SLV",
  "TLT": "TLT",
  "iShares 20+ Year Treasury Bond ETF": "TLT",
  "미국채 20년 ETF": "TLT",
  "미국 장기채 ETF": "TLT",
  "IEF": "IEF",
  "iShares 7-10 Year Treasury Bond ETF": "IEF",
  "미국채 10년 ETF": "IEF",
  "BND": "BND",
  "Vanguard Total Bond Market ETF": "BND",
  "뱅가드 채권 ETF": "BND",
  "IBIT": "IBIT",
  "iShares Bitcoin Trust ETF": "IBIT",
  "비트코인 ETF": "IBIT",
  "아이쉐어즈 비트코인 ETF": "IBIT",
  "FBTC": "FBTC",
  "Fidelity Wise Origin Bitcoin Fund": "FBTC",
  "피델리티 비트코인 ETF": "FBTC",
  "ARKK": "ARKK",
  "ARK Innovation ETF": "ARKK",
  "ARK 이노베이션 ETF": "ARKK",
  "ARKG": "ARKG",
  "ARK Genomic Revolution ETF": "ARKG",
  "SOXX": "SOXX",
  "iShares Semiconductor ETF": "SOXX",
  "반도체 ETF": "SOXX",
  "SMH": "SMH",
  "VanEck Semiconductor ETF": "SMH",
  "반도체 VanEck ETF": "SMH",
  "XLK": "XLK",
  "Technology Select Sector SPDR Fund": "XLK",
  "기술주 섹터 ETF": "XLK",
  "XLF": "XLF",
  "Financial Select Sector SPDR Fund": "XLF",
  "금융 섹터 ETF": "XLF",
  "XLE": "XLE",
  "Energy Select Sector SPDR Fund": "XLE",
  "에너지 섹터 ETF": "XLE",
  "XLV": "XLV",
  "Health Care Select Sector SPDR Fund": "XLV",
  "헬스케어 섹터 ETF": "XLV",
  "XLY": "XLY",
  "Consumer Discretionary Select Sector SPDR Fund": "XLY",
  "임의소비재 섹터 ETF": "XLY",
  "XLP": "XLP",
  "Consumer Staples Select Sector SPDR Fund": "XLP",
  "필수소비재 섹터 ETF": "XLP",
  "XLU": "XLU",
  "Utilities Select Sector SPDR Fund": "XLU",
  "유틸리티 섹터 ETF": "XLU",
  "XLI": "XLI",
  "Industrial Select Sector SPDR Fund": "XLI",
  "산업재 섹터 ETF": "XLI",
  "XLRE": "XLRE",
  "Real Estate Select Sector SPDR Fund": "XLRE",
  "부동산 섹터 ETF": "XLRE",
  "KWEB": "KWEB",
  "KraneShares CSI China Internet ETF": "KWEB",
  "중국인터넷 ETF": "KWEB",
  "EWJ": "EWJ",
  "iShares MSCI Japan ETF": "EWJ",
  "일본 ETF": "EWJ",
  "EEM": "EEM",
  "iShares MSCI Emerging Markets ETF": "EEM",
  "신흥국 ETF": "EEM",
  "VEA": "VEA",
  "Vanguard FTSE Developed Markets ETF": "VEA",
  "선진국 ETF": "VEA",
  "INDA": "INDA",
  "iShares MSCI India ETF": "INDA",
  "인도 ETF": "INDA",
  "MCHI": "MCHI",
  "iShares MSCI China ETF": "MCHI",
  "중국 ETF": "MCHI",
  "VWO": "VWO",
  "Vanguard FTSE Emerging Markets ETF": "VWO",
  "신흥국ETF": "VWO",
  "IWM": "IWM",
  "iShares Russell 2000 ETF": "IWM",
  "러셀2000 ETF": "IWM",
  "중소형주 ETF": "IWM",
  "VUG": "VUG",
  "Vanguard Growth ETF": "VUG",
  "뱅가드 성장주 ETF": "VUG",
  "VYM": "VYM",
  "Vanguard High Dividend Yield ETF": "VYM",
  "뱅가드 고배당 ETF": "VYM",
  "VIG": "VIG",
  "Vanguard Dividend Appreciation ETF": "VIG",
  "뱅가드 배당성장 ETF": "VIG",
  "DGRO": "DGRO",
  "iShares Core Dividend Growth ETF": "DGRO",
  "배당성장 ETF": "DGRO",
  "NOBL": "NOBL",
  "ProShares S&P 500 Dividend Aristocrats ETF": "NOBL",
  "배당귀족 ETF": "NOBL",
  "HDV": "HDV",
  "iShares Core High Dividend ETF": "HDV",
  "고배당 ETF": "HDV",
  "DVY": "DVY",
  "iShares Select Dividend ETF": "DVY",
  "DIVO": "DIVO",
  "Amplify CWP Enhanced Dividend Income ETF": "DIVO",
  "COWZ": "COWZ",
  "Pacer US Cash Cows 100 ETF": "COWZ",
  "캐시카우 ETF": "COWZ",
  "MOAT": "MOAT",
  "VanEck Morningstar Wide Moat ETF": "MOAT",
  "넓은해자 ETF": "MOAT",
  "RSP": "RSP",
  "Invesco S&P 500 Equal Weight ETF": "RSP",
  "S&P500 동일비중 ETF": "RSP",
  "MGK": "MGK",
  "Vanguard Mega Cap Growth ETF": "MGK",
  "메가캡 성장주 ETF": "MGK",
  "QYLD": "QYLD",
  "Global X Nasdaq 100 Covered Call ETF": "QYLD",
  "나스닥100 커버드콜 ETF": "QYLD",
  "XYLD": "XYLD",
  "Global X S&P 500 Covered Call ETF": "XYLD",
  "S&P500 커버드콜 ETF": "XYLD",
  "RYLD": "RYLD",
  "Global X Russell 2000 Covered Call ETF": "RYLD",
  "러셀2000 커버드콜 ETF": "RYLD",
  "QQQI": "QQQI",
  "NEOS Nasdaq-100 High Income ETF": "QQQI",
  "나스닥100 고배당 ETF": "QQQI",
  "SPYI": "SPYI",
  "NEOS S&P 500 High Income ETF": "SPYI",
  "S&P500 고배당 ETF": "SPYI",
  "XDTE": "XDTE",
  "Roundhill S&P 500 0DTE Covered Call ETF": "XDTE",
  "BOTZ": "BOTZ",
  "Global X Robotics & Artificial Intelligence ETF": "BOTZ",
  "로보틱스 AI ETF": "BOTZ",
  "AIQ": "AIQ",
  "Global X Artificial Intelligence & Technology ETF": "AIQ",
  "AI 기술주 ETF": "AIQ",
  "ARKW": "ARKW",
  "ARK Next Generation Internet ETF": "ARKW",
  "ARKF": "ARKF",
  "ARK Fintech Innovation ETF": "ARKF",
  "ARKQ": "ARKQ",
  "ARK Autonomous Technology & Robotics ETF": "ARKQ",
  "ETHE": "ETHE",
  "Grayscale Ethereum Trust ETF": "ETHE",
  "이더리움 ETF": "ETHE",
  "GBTC": "GBTC",
  "Grayscale Bitcoin Trust ETF": "GBTC",
  "그레이스케일 비트코인 ETF": "GBTC",
  "FETH": "FETH",
  "Fidelity Ethereum Fund": "FETH",
  "피델리티 이더리움 ETF": "FETH",

  // ── 비트코인/크립토 관련주 ───────────────────────────────────────────────
  "비트마인": "BMNR",
  "Bit Digital": "BTBT",
  "BTBT": "BTBT",
  "마라톤디지털": "MARA",
  "Marathon Digital": "MARA",
  "MARA": "MARA",
  "라이엇플랫폼스": "RIOT",
  "Riot Platforms": "RIOT",
  "RIOT": "RIOT",
  "클린스파크": "CLSK",
  "CleanSpark": "CLSK",
  "CLSK": "CLSK",
  "코어사이언티픽": "CORZ",
  "Core Scientific": "CORZ",
  "CORZ": "CORZ",
  "아이리스에너지": "IREN",
  "Iris Energy": "IREN",
  "IREN": "IREN",
  "비트팜스": "BITF",
  "Bitfarms": "BITF",
  "BITF": "BITF",
  "사이퍼마이닝": "CIFR",
  "Cipher Mining": "CIFR",
  "CIFR": "CIFR",
  "테라울프": "WULF",
  "TeraWulf": "WULF",
  "WULF": "WULF",
  "허트8": "HUT",
  "Hut 8": "HUT",
  "HUT": "HUT",
  "스트라티스": "STRAT",
  "갤럭시디지털": "GLXY",
  "Galaxy Digital": "GLXY",

  // ── AI/데이터센터/반도체 추가 ─────────────────────────────────────────────
  "사운드하운드": "SOUN",
  "SoundHound": "SOUN",
  "SOUN": "SOUN",
  "아이온Q": "IONQ",
  "IonQ": "IONQ",
  "IONQ": "IONQ",
  "퀀텀컴퓨팅": "QUBT",
  "Quantum Computing": "QUBT",
  "QUBT": "QUBT",
  "디웨이브퀀텀": "QBTS",
  "D-Wave Quantum": "QBTS",
  "QBTS": "QBTS",
  "리게티컴퓨팅": "RGTI",
  "Rigetti Computing": "RGTI",
  "RGTI": "RGTI",
  "퍼플렉시티": "PRPLX",
  "C3.ai": "AI",
  "AI": "AI",
  "어센드러닝": "ACLS",
  "Axcelis Technologies": "ACLS",
  "ACLS": "ACLS",
  "몬도리틱": "MRVI",
  "버티브홀딩스": "VRT",
  "Vertiv": "VRT",
  "VRT": "VRT",
  "비바시스템즈": "VEEV",
  "Veeva Systems": "VEEV",
  "VEEV": "VEEV",
  "워크데이": "WDAY",
  "Workday": "WDAY",
  "WDAY": "WDAY",

  // ── 미국 에너지/원자력 ───────────────────────────────────────────────────
  "오클로": "OKLO",
  "Oklo": "OKLO",
  "OKLO": "OKLO",
  "카멜롯에너지": "CEG",
  "컨스텔레이션에너지": "CEG",
  "Constellation Energy": "CEG",
  "CEG": "CEG",
  "뉴스케일파워": "SMR",
  "NuScale Power": "SMR",
  "SMR": "SMR",
  "탈렌에너지": "TLN",
  "Talen Energy": "TLN",
  "TLN": "TLN",
  "비스트라": "VST",
  "Vistra": "VST",
  "VST": "VST",

  // ── 미국 바이오/제약 추가 ─────────────────────────────────────────────────
  "웨이브라이프사이언스": "WVE",
  "리커전파마슈티컬스": "RXRX",
  "Recursion Pharmaceuticals": "RXRX",
  "RXRX": "RXRX",
  "알엑스오": "RXST",
  "아비나스": "ARVN",
  "Arvinas": "ARVN",
  "ARVN": "ARVN",
  "카탈리스트바이오사이언스": "MCRB",
  "벌칸바이오사이언스": "FULC",
  "크리스퍼테라퓨틱스": "CRSP",
  "CRISPR Therapeutics": "CRSP",
  "CRSP": "CRSP",
  "빔테라퓨틱스": "BEAM",
  "Beam Therapeutics": "BEAM",
  "BEAM": "BEAM",
  "에디타스메디신": "EDIT",
  "Editas Medicine": "EDIT",
  "EDIT": "EDIT",

  // ── 미국 소매/유통 추가 ──────────────────────────────────────────────────
  "크록스": "CROX",
  "Crocs": "CROX",
  "CROX": "CROX",
  "달러제너럴": "DG",
  "Dollar General": "DG",
  "DG": "DG",
  "달러트리": "DLTR",
  "Dollar Tree": "DLTR",
  "DLTR": "DLTR",
  "로스스토어즈": "ROST",
  "Ross Stores": "ROST",
  "ROST": "ROST",
  "TJX": "TJX",
  "TJX Companies": "TJX",

  // ── 미국 자동차 ──────────────────────────────────────────────────────────
  "포드": "F",
  "Ford": "F",
  "제너럴모터스": "GM",
  "General Motors": "GM",
  "GM": "GM",

  // ── 미국 금융 추가 ───────────────────────────────────────────────────────
  "누홀딩스": "NU",
  "Nu Holdings": "NU",
  "NU": "NU",
  "이토로": "ETOR",
  "클로버헬스": "CLOV",

  // ── 미국 우주/모빌리티/신성장 ────────────────────────────────────────────
  "리비안": "RIVN",
  "Rivian": "RIVN",
  "루시드": "LCID",
  "Lucid": "LCID",
  "로켓랩": "RKLB",
  "Rocket Lab": "RKLB",
  "AST스페이스모바일": "ASTS",
  "AST SpaceMobile": "ASTS",
  "조비에비에이션": "JOBY",
  "Joby Aviation": "JOBY",
  "버진갤럭틱": "SPCE",
  "Virgin Galactic": "SPCE",
  "마이크로스트래티지": "MSTR",
  "MicroStrategy": "MSTR",
  "스트라이프": "STRIPE",

  // ── 미국 핀테크/금융 ──────────────────────────────────────────────────────
  "소파이": "SOFI",
  "SoFi": "SOFI",
  "어펌": "AFRM",
  "Affirm": "AFRM",
  "업스타트": "UPST",
  "Upstart": "UPST",
  "마켓액세스": "MKTX",
  "MarketAxess": "MKTX",

  // ── 미국 소비재/미디어/여행 ───────────────────────────────────────────────
  "디즈니": "DIS",
  "Disney": "DIS",
  "부킹홀딩스": "BKNG",
  "Booking Holdings": "BKNG",
  "익스피디아": "EXPE",
  "Expedia": "EXPE",
  "리프트": "LYFT",
  "Lyft": "LYFT",
  "도어대시": "DASH",
  "DoorDash": "DASH",
  "핀터레스트": "PINS",
  "Pinterest": "PINS",
  "스냅": "SNAP",
  "Snap": "SNAP",
  "트위터X": "X",
  "레딧": "RDDT",
  "Reddit": "RDDT",

  // ── 미국 통신 ─────────────────────────────────────────────────────────────
  "AT&T": "T",
  "버라이즌": "VZ",
  "Verizon": "VZ",
  "티모바일": "TMUS",
  "T-Mobile": "TMUS",
  "컴캐스트": "CMCSA",
  "Comcast": "CMCSA",

  // ── 미국 필수소비재/생활용품 ─────────────────────────────────────────────
  "프록터앤드갬블": "PG",
  "Procter & Gamble": "PG",
  "코카콜라": "KO",
  "Coca-Cola": "KO",
  "펩시코": "PEP",
  "PepsiCo": "PEP",
  "필립모리스": "PM",
  "Philip Morris": "PM",
  "알트리아": "MO",
  "Altria": "MO",
  "콜게이트팜올리브": "CL",
  "Colgate-Palmolive": "CL",
  "킴벌리클라크": "KMB",
  "Kimberly-Clark": "KMB",
  "제너럴밀스": "GIS",
  "General Mills": "GIS",

  // ── 미국 산업/항공우주/방산 ──────────────────────────────────────────────
  "보잉": "BA",
  "Boeing": "BA",
  "레이시온": "RTX",
  "RTX": "RTX",
  "록히드마틴": "LMT",
  "Lockheed Martin": "LMT",
  "노스럽그루먼": "NOC",
  "Northrop Grumman": "NOC",
  "GE에어로스페이스": "GE",
  "GE Aerospace": "GE",
  "3M": "MMM",
  "허니웰": "HON",
  "Honeywell": "HON",
  "디어": "DE",
  "Deere": "DE",

  // ── 미국 부동산/인프라 리츠 ──────────────────────────────────────────────
  "아메리칸타워": "AMT",
  "American Tower": "AMT",
  "프롤로지스": "PLD",
  "Prologis": "PLD",
  "웰타워": "WELL",
  "Welltower": "WELL",
  "퍼블릭스토리지": "PSA",
  "Public Storage": "PSA",
  "리얼티인컴": "O",
  "Realty Income": "O",

  // ── 미국 추가 레버리지/인버스 ETF ───────────────────────────────────────
  "TSLQ": "TSLQ",
  "AXS TSLA Bear Daily ETF": "TSLQ",
  "NVDS": "NVDS",
  "T-Rex 2X Inverse NVDA Daily Target ETF": "NVDS",
  "QLD": "QLD",
  "ProShares Ultra QQQ": "QLD",
  "나스닥100 2배": "QLD",
  "SSO": "SSO",
  "ProShares Ultra S&P500": "SSO",
  "S&P500 2배": "SSO",
  "UDOW": "UDOW",
  "ProShares UltraPro Dow30": "UDOW",
  "FNGO": "FNGO",
  "MicroSectors FANG+ Index 2X Leveraged ETN": "FNGO",
  "BULZ": "BULZ",
  "MicroSectors Solactive FANG & Innovation 3X Leveraged ETN": "BULZ",
  "MSFU": "MSFU",
  "T-Rex 2X Long MSFT Daily Target ETF": "MSFU",
  "GOOGL 2X": "GGLL",
  "GGLL": "GGLL",
  "Direxion Daily GOOGL Bull 2X Shares": "GGLL",
  "AMZD": "AMZD",
  "Direxion Daily AMZN Bear 1X Shares": "AMZD",

  // ── 추가 YieldMax ETF ─────────────────────────────────────────────────────
  "OARK": "OARK",
  "YieldMax Innovation Option Income Strategy ETF": "OARK",
  "YMAG": "YMAG",
  "YieldMax Magnificent 7 Fund of Option Income ETFs": "YMAG",
  "YMAX": "YMAX",
  "YieldMax Universe Fund of Option Income ETFs": "YMAX",
  // ── 미국 추가 ETF ─────────────────────────────────────────────────────────
  "SPYG": "SPYG",
  "SPDR Portfolio S&P 500 Growth ETF": "SPYG",
  "VGT": "VGT",
  "Vanguard Information Technology ETF": "VGT",
  "QQQJ": "QQQJ",
  "Invesco NASDAQ Next Gen 100 ETF": "QQQJ",
  "SPDW": "SPDW",
  "SPDR Portfolio Developed World ex-US ETF": "SPDW",

  // ── 유럽 ─────────────────────────────────────────────────────────────────
  "LVMH": "MC",
  "ASML Holding": "ASML",
  "SAP": "SAP",
  "노바티스": "NVS",
  "Novartis": "NVS",
  "로슈": "RHHBY",
  "Roche": "RHHBY",
  "네슬레": "NSRGY",
  "Nestle": "NSRGY",
  "유니레버": "UL",
  "Unilever": "UL",
  "리오틴토": "RIO",
  "Rio Tinto": "RIO",
  "BHP": "BHP",
  "버버리": "BRBY",
  "Burberry": "BRBY",
  "페라리": "RACE",
  "Ferrari": "RACE",
};

// ─── 통합 매핑 (정규화 키) ──────────────────────────────────────────────────

function normalizeName(name: string): string {
  return name
    .replace(/[()（）\s\-·&…]/g, "")
    .replace(/\.+$/, "") // 뒷부분의 줄임표(.) 제거
    .toLowerCase();
}

const _allMap: Record<string, string> = {
  ...KR_NAME_TO_CODE,
  ...FOREIGN_STOCK_MAP,
};

export const TICKER_MAP_NORMALIZED: Record<string, string> = Object.fromEntries(
  Object.entries(_allMap).map(([k, v]) => [normalizeName(k), v])
);

// 미국 주식·ETF 영문명 인덱스 — KR/FOREIGN 미스 시에만 exact + prefix(보수적)로 사용
const US_NORMALIZED: Record<string, string> = Object.fromEntries(
  Object.entries(US_NAME_TO_TICKER).map(([k, v]) => [normalizeName(k), v])
);

export function lookupTicker(name: string): string {
  const normalized = normalizeName(name);

  // 1단계: 정확한 일치
  if (TICKER_MAP_NORMALIZED[normalized]) {
    return TICKER_MAP_NORMALIZED[normalized];
  }

  // 4자 미만은 오탐 방지를 위해 fuzzy 매칭 생략
  if (normalized.length < 4) return "";

  // 2단계: prefix 매칭 — 입력이 등록된 키의 앞부분인 경우
  // 예: "kodex미국배당커버드콜액" → "kodex미국배당커버드콜액티브" 키에 매칭
  let bestPrefixMatch = "";
  let bestPrefixKeyLen = Infinity;
  for (const key of Object.keys(TICKER_MAP_NORMALIZED)) {
    if (key.startsWith(normalized) && key.length < bestPrefixKeyLen) {
      bestPrefixMatch = TICKER_MAP_NORMALIZED[key];
      bestPrefixKeyLen = key.length;
    }
  }
  if (bestPrefixMatch) return bestPrefixMatch;

  // 3단계: suffix 매칭 — 등록된 키가 입력의 앞부분인 경우 (입력이 키보다 긴 경우)
  // 예: "kodex미국배당커버드콜액티브etf" → "kodex미국배당커버드콜액티브" 키에 매칭
  let bestKeyPrefixMatch = "";
  let bestKeyPrefixLen = 0;
  for (const key of Object.keys(TICKER_MAP_NORMALIZED)) {
    if (normalized.startsWith(key) && key.length > bestKeyPrefixLen) {
      bestKeyPrefixMatch = TICKER_MAP_NORMALIZED[key];
      bestKeyPrefixLen = key.length;
    }
  }
  if (bestKeyPrefixMatch) return bestKeyPrefixMatch;

  // 4단계: 부분 일치 (includes) — 입력이 5자 이상이고 키에 포함되는 경우
  // 예: "미국필라델피아반도체" (앞의 TIGER 누락) -> "tiger미국필라델피아반도체나스닥" 매칭
  // 오탐 방지를 위해 입력 문자열이 최소 5자 이상일 때만 적용
  if (normalized.length >= 5) {
    let bestSubstringMatch = "";
    let bestSubstringKeyLen = Infinity;
    for (const key of Object.keys(TICKER_MAP_NORMALIZED)) {
      if (key.includes(normalized) && key.length < bestSubstringKeyLen) {
        bestSubstringMatch = TICKER_MAP_NORMALIZED[key];
        bestSubstringKeyLen = key.length;
      }
    }
    if (bestSubstringMatch) return bestSubstringMatch;
  }

  // 5단계(미국 전용·보수적): exact → prefix(입력이 등록명의 앞부분)만. suffix·substring 미적용
  if (US_NORMALIZED[normalized]) return US_NORMALIZED[normalized];
  let usPrefixMatch = "";
  let usPrefixKeyLen = Infinity;
  for (const key of Object.keys(US_NORMALIZED)) {
    if (key.startsWith(normalized) && key.length < usPrefixKeyLen) {
      usPrefixMatch = US_NORMALIZED[key];
      usPrefixKeyLen = key.length;
    }
  }
  if (usPrefixMatch) return usPrefixMatch;

  return "";
}

// ─── 국내 주식 도메인 매핑 (종목코드→도메인) ──────────────────────────────
// 도메인 확인된 주요 상장사. 나머지는 fallback 이니셜 아이콘 사용.
export const DOMESTIC_STOCK_DOMAIN_MAP: Record<string, string> = {
  // ── 반도체/IT ──────────────────────────────────────────────────────────────
  "005930": "www.samsung.com",
  "000660": "www.skhynix.com",
  "035420": "www.naver.com",
  "035720": "www.kakao.com",
  "323410": "www.kakaobank.com",
  "377300": "www.kakaopay.com",
  "042700": "www.hmsemi.com",
  "009150": "www.samsungelectro-mechanics.com",
  "011070": "www.lginnotek.com",
  // ── 2차전지 ───────────────────────────────────────────────────────────────
  "373220": "www.lgensol.com",
  "006400": "www.samsungsdi.co.kr",
  "051910": "www.lgchem.com",
  "247540": "www.ecoprobm.co.kr",
  "086520": "www.ecopro.co.kr",
  "003670": "www.posco.co.kr",
  // ── 바이오/제약 ───────────────────────────────────────────────────────────
  "207940": "www.samsungbiologics.com",
  "068270": "www.celltrion.com",
  "000100": "www.yuhan.co.kr",
  "128940": "www.hanmipharm.com",
  "069620": "www.daewon.co.kr",
  "185750": "www.ckdpharm.com",
  "006280": "www.greencross.com",
  // ── 금융 ──────────────────────────────────────────────────────────────────
  "105560": "www.kbfg.com",
  "055550": "www.shinhangroup.com",
  "086790": "www.hanafn.com",
  "316140": "www.woorifinancial.co.kr",
  "138040": "www.meritzfire.com",
  "000810": "www.samsungfire.com",
  "005830": "www.idbins.com",
  "039490": "www.kiwoom.com",
  "006800": "securities.miraeasset.com",
  "016360": "www.samsungpop.com",
  "005940": "www.nhqv.com",
  // ── 자동차/운송 ───────────────────────────────────────────────────────────
  "005380": "www.hyundai.com",
  "000270": "www.kia.com",
  "012330": "www.mobis.co.kr",
  "086280": "www.hyundai-glovis.net",
  "003490": "www.koreanair.com",
  "011200": "www.hmm21.com",
  // ── 에너지/소재/화학 ──────────────────────────────────────────────────────
  "005490": "www.posco.co.kr",
  "004020": "www.hyundai-steel.com",
  "010130": "www.koreazinc.co.kr",
  "096770": "www.skinnovation.com",
  "010950": "www.s-oil.com",
  "009830": "www.hanwha.com",
  "267250": "www.hd-hyundai.com",
  // ── 통신 ──────────────────────────────────────────────────────────────────
  "017670": "www.sktelecom.com",
  "030200": "www.kt.com",
  "032640": "www.uplus.co.kr",
  // ── 건설/유통 ─────────────────────────────────────────────────────────────
  "028260": "www.samsungcnt.com",
  "000720": "www.hdec.kr",
  "004170": "www.shinsegae.com",
  "139480": "emart.com",
  "023530": "www.lotteshopping.com",
  // ── 방산/항공우주 ─────────────────────────────────────────────────────────
  "012450": "www.hanwhaaero.com",
  "079550": "www.liguenexone.co.kr",
  "064350": "www.hyundai-rotem.co.kr",
  "047810": "www.kai.co.kr",
  // ── 인터넷/게임 ───────────────────────────────────────────────────────────
  "259960": "www.krafton.com",
  "251270": "www.netmarble.com",
  "036570": "www.ncsoft.com",
  // ── 기타 ──────────────────────────────────────────────────────────────────
  "032830": "www.samsunglife.com",
  "097950": "www.cj.net",
  "352820": "www.hybe.com",
  "041510": "www.smtown.com",
  "035900": "www.jype.com",
};
